CREATE TABLE users(
id INT NOT NULL PRIMARY KEY UNIQUE 	AUTO_INCREMENT,
user_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
name VARCHAR(100) NOT NULL,
user_email VARCHAR(100) NOT NULL,
user_password VARCHAR(100) NOT NULL,
user_role VARCHAR(100));

CREATE TABLE Incident(
id INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
subject VARCHAR(300) NOT NULL,
description VARCHAR(600),
sevirity VARCHAR(100),
status VARCHAR(100),
created_by INT NOT NULL,
last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE Events(
id INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT,
incident_id INT NOT NULL,
action_description VARCHAR(500) NOT NULL,
status VARCHAR(100)
);



